version: "3.1"

services:
  jupyternotebook:
    container_name: healthcan_app
    image: healthcan/app
    build:
      context: jupyternotebook
      dockerfile: ./Dockerfile
    command:
      python hc_server.py
    ports:
      - 3000:3000
    volumes:
      - $PWD/app:/root/app
    working_dir: /root/app
    networks: 
      - container-link
  db:
    container_name: healthcan_db
    build:
      context: db
      dockerfile: ./Dockerfile
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/access.cnf:/home/access.cnf
    env_file:
      - ./db/.env.db
    networks: 
      - container-link

networks:
  default:
    external:
      name: bridge
  container-link:
    name: healthcan_link
