#######################################
# DESCRIPTION: Dockerfile for healthcan
# CONTAINER: MySQL
# OWNER: RenGoto
#######################################
FROM mysql:5.7.27
MAINTAINER "Ren Goto" <r0719en@pluslab.org>

COPY charaset.cnf /etc/mysql/conf.d/
